var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/glossary/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vdh0fh._.js")
R.c("server/chunks/ssr/lib_glossary_ts_0scne5k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0.cmrhc.js")
R.c("server/chunks/ssr/_0hsfzre._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06kg3ad._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~q40dp._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_glossary_[slug]_page_actions_059v6se.js")
R.m(69693)
module.exports=R.m(69693).exports
